---
title: "Benchmarking on cross-species data"
author: "Zhiyuan"
date: "9/16/2020 (last modified: `r Sys.Date()`)"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.width = 12, fig.keep = TRUE, fig.path = "../plots/pancreas_twospecies/Rmarkdown_")
knitr::opts_knit$set(root.dir = "~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration")

library(Seurat)
library(batchelor)
library(scater)
library(scran)
library(SingleCellExperiment)
library(harmony)
library(limma)
library(reticulate)
library(mclust)

library(ggplot2)
library(cowplot)
library(RColorBrewer)

source("~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration/functions_simulate.R")
source("~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration/functions_pipelines.R")
source("~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration/functions_initial.R")

verbose <- FALSE
dirsave <- "pancreas_twospecies"

n <- 60
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
```

# Read data

```{r read-data}
# dataset 4: pancreas
seu <- readRDS(paste0("rdata/",dirsave,"/seurat_object_preprocessed.rds"))
df_ari <- read.csv(paste0("plots/ari/",dirsave,"_ari.csv"))
clustering_res <- readRDS(paste0("rdata/",dirsave,"/clustering_res_metaclustering.rds"))
```


# Other integration pipelines

## CCA correction

```{r cca-correction, message=FALSE, warning=FALSE, fig.width=8, fig.height=4}
df_ari$runtime[df_ari$method == "cca"] <- system.time({
  seu.integrated <- cca_integration(seu)
  seu.integrated <- FindNeighbors(seu.integrated, dims = 1:15)
  seu.integrated <- FindClusters(seu.integrated, resolution = 0.4)
})[3]
seu.integrated$cluster <- as.factor(seu.integrated$seurat_clusters)

df_ari$ARI[df_ari$method == "cca"] <- adjustedRandIndex(seu.integrated$Group, seu.integrated$cluster)
df_ari$batch_ARI[df_ari$method == "cca"] <- adjustedRandIndex(seu.integrated$Batch, seu.integrated$cluster)
clustering_res$cca <- seu.integrated$cluster[match(clustering_res$cell, colnames( seu.integrated))]

# plot
df_plot <- data.frame(V1 = seu.integrated@reductions$tsne@cell.embeddings[,1],
                      V2 = seu.integrated@reductions$tsne@cell.embeddings[,2],
                      label = seu.integrated$Group,
                      cluster = seu.integrated$cluster,
                      batch = seu.integrated$Batch)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic()  + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(cluster))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:30])
p3 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10])
p1 + p2 + p3

# ggsave(paste0("plots/",dirsave,"/tsne_cca.pdf"), width = 12, height = 4.5, useDingbats = FALSE)
```



## MNN correction

```{r mnn-correction, fig.width=8, fig.height=4}
df_ari$runtime[df_ari$method == "mnn"] <- system.time({
  f.out <- mnn_integration(seu)
  seu.integrated@reductions$pca@cell.embeddings <- reducedDim(f.out, "corrected")
  seu.integrated <- FindNeighbors(seu.integrated, dims = 1:15)
  seu.integrated <- FindClusters(seu.integrated, resolution = 0.4)
  f.out$cluster <- as.factor(seu.integrated$seurat_clusters)
})[3]

# record ARIs
df_ari$ARI[df_ari$method == "mnn"] <- adjustedRandIndex(f.out$Group, f.out$cluster)
df_ari$batch_ARI[df_ari$method == "mnn"] <- adjustedRandIndex(f.out$Batch, f.out$cluster)
clustering_res$mnn <- f.out$cluster[match(clustering_res$cell, colnames( f.out))]

# plots
df_plot <- data.frame(V1 = reducedDim(f.out, "TSNE")[,1],
                      V2 = reducedDim(f.out, "TSNE")[,2],
                      label = f.out$Group,
                      cluster = f.out$cluster,
                      batch = f.out$Batch)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic() + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(cluster))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:30])
p3 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10])
p1 + p2 + p3
# ggsave(paste0("plots/",dirsave,"/tsne_mnn.pdf"), width = 12, height = 4.5, useDingbats = FALSE)
```

## scanorama

```{r run-scanorama, fig.width=8, fig.height=4}
# List of datasets (matrices of cells-by-genes):
# https://github.com/brianhie/scanorama/issues/38
datasets <- list(t(as.matrix(seu@assays$RNA@counts[,seu$Batch == unique(seu$Batch)[1]])),
                 t(as.matrix(seu@assays$RNA@counts[,seu$Batch == unique(seu$Batch)[2]])))
# List of gene lists:
genes_list <- list(rownames(seu),rownames(seu))

scanorama <- import('scanorama')
# Integration
df_ari$runtime[df_ari$method == "scanorama"] <- system.time({
  integrated.data <- scanorama$integrate(datasets, genes_list)
  tmp <- t(integrated.data[[1]][[1]])
  tmp <- cbind(tmp,  t(integrated.data[[1]][[2]]))
  
  colnames(tmp) <- c(colnames(seu@assays$RNA@counts[,seu$Batch == unique(seu$Batch)[1]]), colnames(seu@assays$RNA@counts[,seu$Batch == unique(seu$Batch)[2]]))
  tmp <- t(tmp)
  tmp <- tmp[match(colnames(seu.integrated), rownames(tmp)),]
  seu.integrated@reductions$pca@cell.embeddings <- tmp
  seu.integrated <- FindNeighbors(seu.integrated, dims = 1:15)
  seu.integrated <- FindClusters(seu.integrated, resolution = 0.4)
})[3]

# run tSNE
df_scanorama <- RunTSNE(tmp[,1:50])
# record ARIs
df_ari$ARI[df_ari$method == "scanorama"] <- adjustedRandIndex(seu$Group, seu.integrated$seurat_clusters)
df_ari$batch_ARI[df_ari$method == "scanorama"] <- adjustedRandIndex(seu$Batch, seu.integrated$seurat_clusters)
clustering_res$scan <- seu.integrated$seurat_clusters[match(clustering_res$cell, colnames(seu.integrated))]

rm(datasets)
rm(genes_list)
rm(integrated.data)

## plots
df_plot <- data.frame(V1 = df_scanorama@cell.embeddings[,1],
                      V2 = df_scanorama@cell.embeddings[,2],
                      label = seu$Group,
                      cluster = as.factor(seu.integrated$seurat_clusters),
                      batch = seu$Batch)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic()  + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank())+ scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(cluster))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank())+ scale_color_manual(values = col_vector[10:30])
p3 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank())+ scale_color_manual(values = col_vector[1:10])
p1 + p2 + p3
# ggsave(paste0("plots/",dirsave,"/tsne_scanorama.pdf"), width = 12, height = 4.5,  useDingbats = FALSE)
```

## Harmony

```{r harmony-correction, message=FALSE, warning=FALSE, fig.width=8, fig.height=4}
df_ari$runtime[df_ari$method == "harmony"] <- system.time({
  seu.integrated <- RunHarmony(seu, "Batch")
  seu.integrated <- FindNeighbors(seu.integrated, dims = 1:15, reduction = "harmony")
  seu.integrated <- FindClusters(seu.integrated, resolution = 0.4)
  seu.integrated$cluster <- as.factor(seu.integrated$seurat_clusters)
})[3]

df_ari$ARI[df_ari$method == "harmony"] <- adjustedRandIndex(seu.integrated$Group, seu.integrated$cluster)
df_ari$batch_ARI[df_ari$method == "harmony"] <- adjustedRandIndex(seu.integrated$Batch, seu.integrated$cluster)
clustering_res$harmony <- seu.integrated$cluster[match(clustering_res$cell, colnames( seu.integrated))]

# plot
seu.integrated <- RunTSNE(seu.integrated, reduction = "harmony")
df_plot <- data.frame(V1 = seu.integrated@reductions$tsne@cell.embeddings[,1],
                      V2 = seu.integrated@reductions$tsne@cell.embeddings[,2],
                      label = seu.integrated$Group,
                      cluster = seu.integrated$cluster,
                      batch = seu.integrated$Batch)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic()  + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(cluster))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:30])
p3 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10])
p1 + p2 + p3
ggsave(paste0("plots/",dirsave,"/tsne_harmony.pdf"), width = 12, height = 4.5, useDingbats = FALSE)
```

# Other clustering pipeline

## Seurat

```{r seurat-clustering-pipeline, fig.width=8, fig.height=4}
df_ari$runtime[df_ari$method == "seurat"] <- system.time({
seu <- seurat_clustering(seu_obj = seu, res = 0.4)
})[3]

# record ARIs
df_ari$ARI[df_ari$method == "seurat"] <- adjustedRandIndex(seu$seurat_cluster, seu$Group)
df_ari$batch_ARI[df_ari$method == "seurat"] <- adjustedRandIndex(seu$seurat_cluster, seu$Batch)
clustering_res$seurat <- seu$seurat_cluster[match(clustering_res$cell, colnames(seu))]
  
# plot
df_plot <- data.frame(V1 = seu@reductions$tsne@cell.embeddings[,1],
                      V2 = seu@reductions$tsne@cell.embeddings[,2],
                      label = seu$Group,
                      cluster = seu$seurat_cluster,
                      batch = seu$Batch)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic()  + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank())+ scale_color_manual(values = col_vector[1:10])
p3 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(cluster))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_grid(p1, p2, p3, ncol = 3)
```

## SC3

```{r SC3-clustering-pipeline}
set.seed(12345)
select <- sample(1:ncol(seu), ncol(seu)/10, replace = FALSE)
seu2 <- seu[,select]
n_groups <- length(unique(seu[,select]$Group))

df_ari$runtime[df_ari$method == "sc3"] <- system.time({
  seu2 <- sc3_clustering(seu_obj = seu2, g = n_groups)
})[3]

# record ARIs
df_ari$ARI[df_ari$method == "sc3"] <- adjustedRandIndex(seu2$sc3_cluster, seu2$Group)
df_ari$batch_ARI[df_ari$method == "sc3"] <- adjustedRandIndex(seu2$sc3_cluster, seu2$Batch)
clustering_res$sc3 <- seu2$sc3_cluster[match(clustering_res$cell, colnames(seu2))]
```

## RaceID

```{r raceid-clustering}
df_ari$runtime[df_ari$method == "raceid"] <- system.time({
  seu2 <- raceid_clustering(seu_obj = seu2, g = n_groups)
})[3]

# record ARIs
df_ari$ARI[df_ari$method == "raceid"] <- adjustedRandIndex(seu2$raceID_cluster, seu2$Group)
df_ari$batch_ARI[df_ari$method == "raceid"] <- adjustedRandIndex(seu2$raceID_cluster, seu2$Batch)
clustering_res$raceid <- seu2$raceID_cluster[match(clustering_res$cell, colnames(seu2))]
```




# Conclusion

```{r summary-tsne-plots, fig.width=15, fig.height=7.5}
df_plot <- data.frame(V1 = seu@reductions$tsne@cell.embeddings[,1],
                      V2 = seu@reductions$tsne@cell.embeddings[,2])
df_plot <- cbind(df_plot, clustering_res[match(colnames(seu), clustering_res$cell),])
plot_list <- list()

plot_list[[1]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10])
plot_list[[2]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:20])
plot_list[[3]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(ours_denovo))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[4]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(ours_assisted))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[5]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(cca))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[6]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(mnn))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[7]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(scan))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[8]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(harmony))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[9]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(seurat))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[10]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(sc3))) + geom_point(alpha = 0.6, size=1.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_list[[11]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(raceid))) + geom_point(alpha = 0.6, size=1.5)  +  theme_classic() + theme(legend.position = "top") +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40])
plot_grid(plotlist = plot_list, ncol = 6)
ggsave(paste0("plots/",dirsave,"/tsne_clusters_all.pdf"), width = 23, height = 9, useDingbats = FALSE)
```


```{r}
for(i in 1:length(plot_list)){
  plot_list[[i]] <- plot_list[[i]] + xlab("t-SNE 1") + ylab("t-SNE 2") + theme(legend.position =  "none")
}
plot_grid(plotlist = plot_list, ncol = 6)
ggsave(paste0("plots/",dirsave,"/tsne_clusters_all_nolegend.pdf"), width = 23, height = 7.2, useDingbats = FALSE)
```


```{r print-table-df_ari}
# Adjusted Rand index
saveRDS(clustering_res, paste0("rdata/",dirsave,"/clustering_res.rds"), compress = TRUE)
write.csv(df_ari, paste0("plots/ari/",dirsave,"_ari.csv"), row.names = FALSE)
knitr::kable(df_ari)
```

# Technical

```{r sessionInfo}
sessionInfo()
```

