---
title: "Benchmarking on COVID data"
author: "Zhiyuan"
date: "26 Jan 2021 (last modified: `r Sys.Date()`)"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.width = 12, fig.keep = TRUE, fig.path = "../plots/covid19/Rmarkdown_")
knitr::opts_knit$set(root.dir = "~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration")

library(Seurat)
library(ggplot2)
library(cowplot)
library(RColorBrewer)

verbose <- FALSE
dirsave <- "covid19"
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
```

# Read data and results

```{r read-data}
seu <- readRDS(paste0("rdata/",dirsave,"/seurat_object_preprocessed.rds"))
methods <- c("asCIDER", "dnCIDER", "CCA", "MNN", "scanorama", "harmony","seurat", "sc3", "raceid")
df_ari <- c()
clustering_res <- data.frame(sample = colnames(seu))
for(i in 1:length(methods)){
  ari_tmp <- readRDS(paste0("rdata/", dirsave, "/", methods[i],"_ARI_res.rds"))
  cluster_tmp <- readRDS(paste0("rdata/", dirsave, "/", methods[i],"_clustering_res.rds"))
  df_ari <- rbind(df_ari, ari_tmp)
  clustering_res <- cbind(clustering_res, cluster_tmp[match(clustering_res$sample, cluster_tmp[, 1]), 2])
}
colnames(clustering_res) <- c("sample", methods)
dim(seu)
```

# Barplots

```{r}
ggplot(df_ari, aes(x = method, y = ARI)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(ARI, 2)),
            vjust = 1.6,
            color = "white",
            size = 3.5) + theme_linedraw() + xlab("") +
  theme(axis.text.x = element_text(angle = 20, vjust = 0.8))
ggsave(paste0("plots/ari/",dirsave,"_ari.pdf"), width = 4, height = 3)
```

```{r}
p1 <- ggplot(df_ari, aes(x = method, y = 1-batch_ARI))  +
  geom_bar(stat="identity", fill="steelblue") +
  geom_text(aes(label=round(1-batch_ARI, 2)), vjust=1.6, color="white", size=3.5) + theme_linedraw() + xlab("")
p2 <- ggplot(df_ari, aes(x = method, y = runtime))  +
  geom_bar(stat="identity", fill="steelblue") +
  geom_text(aes(label=round(runtime, 1)), vjust=1.6, color="white", size=3.5) + theme_linedraw() + xlab("")
plot_grid(p1, p2)
ggsave(paste0("plots/ari/",dirsave,"_batchARI_runtime.pdf"), width = 10, height = 3)
```



# Conclusion

```{r summary-tsne-plots, fig.width=15, fig.height=7.5}
df_plot <- data.frame(V1 = seu@reductions$tsne@cell.embeddings[,1],
                      V2 = seu@reductions$tsne@cell.embeddings[,2])
df_plot <- cbind(df_plot, clustering_res[match(colnames(seu), clustering_res[,1]),])
df_plot$batch <- seu$Batch_name
df_plot$label <- seu$cell_type
plot_list <- list()

plot_list[[1]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10]) + labs(col = "")
plot_list[[2]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:20]) + labs(col = "")
plot_list[[3]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(dnCIDER))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[4]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(asCIDER))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[5]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(CCA))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[6]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(MNN))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[7]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(scanorama))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[8]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(harmony))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")

plot_list[[9]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(seurat))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[10]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(sc3))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")
plot_list[[11]] <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(raceid))) + geom_point(alpha = 0.6, size=0.5)  +  theme_classic() + theme(legend.position = "top", legend.background = element_blank()) +  theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[10:40]) + labs(col = "")

plot_grid(plotlist = plot_list, ncol = 6)
ggsave(paste0("plots/",dirsave,"/tsne_clusters_all.pdf"), width = 22, height = 9)
```


```{r}
for(i in 1:length(plot_list)){
  plot_list[[i]] <- plot_list[[i]] + xlab("t-SNE 1") + ylab("t-SNE 2") + theme(legend.position =  "none")
}
plot_grid(plotlist = plot_list, ncol = 6)
ggsave(paste0("plots/",dirsave,"/tsne_clusters_all_nolegend.pdf"), width = 22, height = 7.2, useDingbats = FALSE)
```


```{r print-table-df_ari}
# Adjusted Rand index
saveRDS(clustering_res, paste0("rdata/",dirsave,"/clustering_res.rds"), compress = TRUE)
write.csv(df_ari, paste0("plots/ari/",dirsave,"_ari.csv"), row.names = FALSE)
knitr::kable(df_ari)
```

# asCIDER: Dendrogram

```{r}
df_transfer <- data.frame(id = paste0(seu$Group, "_", seu$Batch),
                          name = paste0(seu$cell_type, " (", seu$Batch_name, ")"))
df_transfer <- unique(df_transfer)
```
```{r}
dist_coef <- readRDS(paste0("rdata/", dirsave, "/asCIDER_dist_coef.rds"))
# Distance matrix
tmp <- dist_coef + t(dist_coef)
diag(tmp) <- 1

colnames(tmp) <- rownames(tmp) <- df_transfer$name[match(rownames(tmp),  df_transfer$id)]
```


```{r dendrogram-RBC}
celltypes <- c("RBC", "DC", "classical Monocyte", "B cell, IgG+", "NK cell", "CD8, non-EM-like", "CD8, EM-like", "nonclassical Monocyte")
for(itor in celltypes){
  idx <- startsWith(rownames(tmp), itor)
  hc <- hclust(as.dist(1 - tmp[idx, idx]))
  dhc <- as.dendrogram(hc)
  
  specific_leaf <- dhc[[1]][[1]][[1]]
  
  # To color each leaf
  i = 0
  colLab <<- function(n) {
    if (is.leaf(n)) {
      a <- attributes(n)
      ligne <- match(attributes(n)$label, paste0(seu$cell_type, " (", seu$Batch_name, ")"))
      batch <- seu$Batch[ligne]
      
      if (batch == "Batch1") {
        col_batch = col_vector[23]
      } else if (batch == "Batch2") {
        col_batch = col_vector[20]
      } else if (batch == "Batch3") {
        col_batch = col_vector[26]
      } else if (batch == "Batch4") {
        col_batch = col_vector[24]
      } else if (batch == "Batch5") {
        col_batch = col_vector[46]
      }
      #Modification of leaf attribute
      attr(n, "nodePar") <- c(a$nodePar, list(cex = 1.5, lab.cex = 0.9, pch = 20, col = col_batch, lab.font = 1, lab.cex = 1))
    }
    return(n)
  }
  
  dL <- dendrapply(dhc, colLab)
  
  # And the plot
  if(itor == "RBC"){
    pdf(paste0("plots/",dirsave,"/metaclustering/asCIDER_dendrogram_", gsub(pattern = ",", "", itor), ".pdf"), width = 5.5, height = 3, useDingbats = FALSE)
    par(mar= c(5.1, 4.1, 4.1, 12))
    plot(dL , main="",horiz=T)
    legend("topleft", 
           legend = c("Asymptomatic COVID-19" , "Healthy Donor" , "Influenza" , "mild COVID-19" , "severe COVID-19"), 
           col = col_vector[c(23,20,26,24,46)], 
           pch = 20, bty = "n",  pt.cex = 1.5, cex = 0.8 , 
           text.col = "black", horiz = FALSE, inset = 0)
    dev.off()
  } else {
    pdf(paste0("plots/",dirsave,"/metaclustering/asCIDER_dendrogram_", gsub(pattern = ",", "", itor), ".pdf"), width = 5.5, height = 3, useDingbats = FALSE)
    par(mar= c(5.1, 4.1, 4.1, 12))
    plot(dL , main="",horiz=T)
    dev.off()
  }
}

```


# Technical

```{r sessionInfo}
sessionInfo()
```

