---
title: "Integration of hematopoietic progenitors"
author: "Zhiyuan"
date: "10/21/2020 (last modified: `r Sys.Date()`)"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.width = 9, fig.keep = FALSE, fig.path = "plots/progenitor/integration/Rmarkdown_")
knitr::opts_knit$set(root.dir = "~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration")

library(Seurat)

library(limma)
library(edgeR)
library(mclust)

library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(igraph)
library(viridis)

library(lisi)
library(harmony)

source("~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration/functions_simulate.R")
source("~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration/functions_pipelines.R")
source("~/OneDrive - Nexus365/Project ClinCluster/evaluate-integration/evaluate-integration/functions_initial.R")

verbose <- FALSE
dirsave <- "progenitor"

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
```

# Summary

Integrate progenitor data by CCA and evaluate.

# Read data

```{r read-data}
seu <- readRDS(paste0("rdata/",dirsave,"/seurat_object_preprocessed_selected.rds"))
```

```{r, message=FALSE, warning=FALSE, fig.width=8, fig.height=4}
df_plot <- data.frame(PC1 = seu@reductions$pca@cell.embeddings[,1],
                      PC2 = seu@reductions$pca@cell.embeddings[,2],
                      label = seu$Group,
                      batch = seu$Batch,
                      group = paste0(seu$Group, "_", seu$Batch))
p1 <- ggplot(df_plot, aes(x = PC1, y = PC2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic()  + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = PC1, y = PC2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10])
p3 <- ggplot(df_plot, aes(x = PC1, y = PC2, col = as.factor(group))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[17:22])
p1 + p2 + p3
ggsave(paste0("plots/",dirsave,"/evaluation/PCA_uncorrected.pdf"), width = 18, height = 6.5, useDingbats = FALSE)
```

# CCA correction

```{r cca correction}
seu.integrated <- cca_integration(seu)
```

```{r, message=FALSE, warning=FALSE, fig.width=8, fig.height=4}
df_plot <- data.frame(V1 = seu.integrated@reductions$pca@cell.embeddings[,1],
                      V2 = seu.integrated@reductions$pca@cell.embeddings[,2],
                      label = seu.integrated$Group,
                      batch = seu.integrated$Batch)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(label))) + geom_point(alpha = 0.6, size=1) + theme_classic()  + theme(legend.position = "top",axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(breaks = unique(seu$Group), values = col_vector[1:20])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, col = as.factor(batch))) + geom_point(alpha = 0.6, size=1)  +  theme_classic() + theme(legend.position = "top") + theme(axis.ticks.x = element_blank(),axis.ticks.y = element_blank(),axis.text = element_blank()) + scale_color_manual(values = col_vector[1:10])
p1 + p2
# ggsave(paste0("plots/",dirsave,"/evaluation/tsne_cca_PCAplots.pdf"), width = 12, height = 4.5, useDingbats = FALSE)
```

## Evalutation


```{r diffusionmap}
set.seed(12345)
dm <- destiny::DiffusionMap(seu.integrated@reductions$pca@cell.embeddings[,1:15])
```


```{r cca cluster}
res <- dbscan::hdbscan(seu.integrated@reductions$pca@cell.embeddings[,1:15], minPts = 50)
# res <-  kernlab::specc(seu.integrated@reductions$pca@cell.embeddings, centers = 3)
seu.integrated$cluster <- as.factor(res$cluster)
seu.integrated$cluster <- as.factor(seu.integrated$cluster)

table(seu.integrated$Group, seu.integrated$cluster)
```



```{r cca-evaluation}
seu.integrated$initial_cluster <- paste0(seu.integrated$cluster, "_",seu.integrated$Batch)
tmp <- seu.integrated@meta.data[,colnames(seu.integrated@meta.data) == "initial_cluster"]

## merge seurat list
metadata <- data.frame(label = tmp, batch = seu$Batch, stringsAsFactors = FALSE)
select <- downsampling(metadata = metadata, n_size = 40, include = TRUE, replace = TRUE)

matrix <- as.matrix(seu@assays$RNA@counts[ , select])
colnames(matrix) <- paste0(colnames(matrix), 1:ncol(matrix)) # avoid duplication
keep <- rowSums(matrix > 0.5) > 5
dge <- edgeR::DGEList(counts = matrix[keep, , drop = FALSE]) # make a edgeR object
dge <- dge[!grepl("ERCC-", rownames(dge)), ] # remove ERCC
dge <- dge[!grepl("MT-", rownames(dge)), ]

df <- data.frame(g = metadata$label[select],
                 b = metadata$batch[select], ## batch
                 stringsAsFactors = F) ## label

df$detrate <- scale(colMeans(matrix > 0))[, 1]
rownames(df) <- colnames(matrix)

N <- length(unique(df$g)) # number of groups
# get the dataframe of combinations/pairs for comparison
combinations <- data.frame(g1 = rep(unique(df$g), each = N), 
                           g2 = rep(unique(df$g), N), stringsAsFactors = FALSE)
combinations <- combinations[combinations$g1 != combinations$g2, ]
combinations$b1 <- df$b[match(combinations$g1, df$g)]
combinations$b2 <- df$b[match(combinations$g2, df$g)]
combinations <- combinations[combinations$b1 != combinations$b2, ]
idx <- c()
for (i in 2:nrow(combinations)) {
  if (!combinations$g2[i] %in% combinations$g1[1:(i - 1)]) {
    idx <- c(idx, i)
  }
}
combinations <- combinations[c(1, idx), ]
rownames(combinations) <- 1:nrow(combinations)

dist_p <- dist_t <- dist_coef <- matrix(0, nrow = N, ncol = N)
colnames(dist_p) <- rownames(dist_p) <- unique(df$g)
colnames(dist_t) <- rownames(dist_t) <- unique(df$g)
colnames(dist_coef) <- rownames(dist_coef) <- unique(df$g)

# create progress bar
if (verbose == TRUE) {
  pb <- txtProgressBar(min = 0, max = nrow(combinations), style = 3)
  k <- 1
}

for (i in 1:nrow(combinations)) {
  if (verbose == TRUE) {
    setTxtProgressBar(pb, k) # progress bar
    k <- k + 1
  }
  
  df$tmp <- "bg"
  df$tmp[df$g == combinations$g1[i]] <- "g1"
  df$tmp[df$g == combinations$g2[i]] <- "g2"
  
  design <- model.matrix(~ 0 + tmp + b + detrate, data = df)
  contrast_m <- makeContrasts(contrasts = c("tmpg1-tmpbg", "tmpg2-tmpbg"), levels = design)
  group_fit <- getGroupFit(dge, design, contrast_m, method = "trend") # limma trend
  
  idx1 <- rownames(dist_coef) == combinations$g1[i]
  idx2 <- colnames(dist_coef) == combinations$g2[i]
  dist_coef[idx1, idx2] <- cor(coef(group_fit)[, 1], coef(group_fit)[, 2])
  dist_t   [idx1, idx2] <- cor(group_fit$t[, 1], group_fit$t[, 2])
  dist_p   [idx1, idx2] <- cor(-log10(group_fit$p.value)[, 1] * sign(coef(group_fit)[, 1]),
                               -log10(group_fit$p.value)[, 2] * sign(coef(group_fit)[, 2])
  )
  
}
if (verbose == TRUE) {
  close(pb) # close progress bar
}
```

## Network

```{r cca-integration-network}
df_plot <- data.frame(g = seu.integrated$cluster[select], # colour.by
                      b = seu.integrated$Batch[select], # batch
                      c = seu.integrated$initial_cluster[select], # label; initial cluster
                      stringsAsFactors = FALSE)

df_plot$combination <- paste0(df_plot$g, "-", df_plot$c)
freq <- table(df_plot$combination)
df_plot$freq <- freq[match(df_plot$combination, names(freq))]
df_plot <- df_plot[order(df_plot$freq, decreasing = TRUE), ]
df_plot <- unique(df_plot)

edges <- data.frame(from = combinations$g1, to = combinations$g2, weight = NA) # edges
tmp <- dist_coef + t(dist_coef)
for (i in 1:nrow(edges)) {
  edges$weight[i] <- tmp[rownames(tmp) == edges$from[i], colnames(tmp) == edges$to[i]]
}
edges$weight[edges$weight < 0] <- 0
edges <- edges[edges$weight > 0, ]
net <- igraph::graph_from_data_frame(edges, directed = FALSE)
E(net)$width <- 2^(E(net)$weight * 5)
vg_names <- attr(V(net), "names")

df_plot_cols <- data.frame(group = unique(df_plot$g),
                           col = col_vector[1:length(unique(df_plot$g))], stringsAsFactors = FALSE)
df_plot$col <- df_plot_cols$col[match(df_plot$g, df_plot_cols$group)]
V(net)$color <- df_plot$col[match(vg_names, df_plot$c)]

V(net)$frame.color <- "#777777"
V(net)$size <- 20 
V(net)$label.family <- "Helvetica"

plot(net); legend(
  x = -1.5, y = -1.1, df_plot_cols$group, pch = 21,
  col = "#777777", pt.bg = df_plot_cols$col, pt.cex = 2, cex = .8, bty = "n", ncol = 2
)
```

```{r cca-integration-heatmap}
groups <- c(0:2)
idx1 <- paste0(groups, "_Batch1")
idx2 <- paste0(groups, "_Batch2")
tmp <- dist_coef + t(dist_coef)
diag(tmp) <- 1
pheatmap::pheatmap(
  tmp[idx1, idx2],
  border_color = "grey20",
  color = viridis::inferno(50),
  display_numbers = TRUE,
  cluster_rows = FALSE,
  cluster_cols = FALSE
)
```


## tSNE plot

```{r cca-plot, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}
df_plot <- data.frame(Dimension_1 = dm@eigenvectors[,1],
                      Dimension_2 = dm@eigenvectors[,2],
                      label = seu.integrated$Group,
                      batch = seu.integrated$Batch,
                      cluster = seu.integrated$cluster)
for(i in 1:nrow(df_plot)) {
  df_plot$similarity[i] <- tmp[paste0(df_plot$cluster[i], "_Batch1"), paste0(df_plot$cluster[i], "_Batch2")]
}
p1 <- ggplot(df_plot, aes(x = Dimension_1, y = Dimension_2, fill = as.factor(label))) + geom_point(col = "grey40", size = 2, shape = 21) + theme_classic()  + theme(legend.position = "top") +  scale_fill_manual(breaks = unique(seu$Group), values = col_vector[1:3])
p2 <- ggplot(df_plot, aes(x = Dimension_1, y = Dimension_2, fill = as.factor(batch))) + geom_point(col = "grey40", size = 2, shape = 21)  +  theme_classic() + theme(legend.position = "top")  + scale_fill_manual(values = col_vector[9:10])
p3 <- ggplot(df_plot, aes(x = Dimension_1, y = Dimension_2, fill = as.factor(cluster))) + geom_point(col = "grey40", size = 2, shape = 21)  +  theme_classic() + theme(legend.position = "top") + scale_fill_manual(values = col_vector[6:8])
p4 <- ggplot(df_plot, aes(x = Dimension_1, y = Dimension_2, fill = similarity)) + geom_point(col = "grey40", size = 2, shape = 21)  +  theme_classic() + theme(legend.position = "top")  +  scale_fill_viridis(option = "B")
p1 + p2 + p3 + p4
ggsave(paste0("plots/",dirsave,"/evaluation/tsne_cca_DBSCAN_clustered.pdf"), width = 10, height = 10, useDingbats = FALSE)
```

## Violin plot

```{r}
p1 <- ggplot(df_plot, aes(x = label, y = similarity)) + geom_violin(scale = "width") + theme_classic() + xlab("") 
p1 
ggsave(paste0("plots/",dirsave,"/evaluation/asCIDER_violinplot_similarityByTypes.pdf"), useDingbats = FALSE, width = 4, height = 2)
```


# Distance by original cell annotations

```{r cider-evaluation}
seu.integrated$initial_cluster <- paste0(seu.integrated$Group, "_",seu.integrated$Batch)
tmp <- seu.integrated@meta.data[,colnames(seu.integrated@meta.data) == "initial_cluster"]

## merge seurat list
metadata <- data.frame(label = tmp, batch = seu$Batch, stringsAsFactors = FALSE)
select <- downsampling(metadata = metadata, n_size = 40, include = TRUE, replace = TRUE)

matrix <- as.matrix(seu@assays$RNA@counts[ , select])
colnames(matrix) <- paste0(colnames(matrix), 1:ncol(matrix)) # avoid duplication
keep <- rowSums(matrix > 0.5) > 5
dge <- edgeR::DGEList(counts = matrix[keep, , drop = FALSE]) # make a edgeR object
dge <- dge[!grepl("ERCC-", rownames(dge)), ] # remove ERCC
dge <- dge[!grepl("MT-", rownames(dge)), ]

df <- data.frame(g = metadata$label[select],
                 b = metadata$batch[select], ## batch
                 stringsAsFactors = F) ## label

df$detrate <- scale(colMeans(matrix > 0))[, 1]
rownames(df) <- colnames(matrix)

N <- length(unique(df$g)) # number of groups
# get the dataframe of combinations/pairs for comparison
combinations <- data.frame(g1 = rep(unique(df$g), each = N), 
                           g2 = rep(unique(df$g), N), stringsAsFactors = FALSE)
combinations <- combinations[combinations$g1 != combinations$g2, ]
combinations$b1 <- df$b[match(combinations$g1, df$g)]
combinations$b2 <- df$b[match(combinations$g2, df$g)]
combinations <- combinations[combinations$b1 != combinations$b2, ]
idx <- c()
for (i in 2:nrow(combinations)) {
  if (!combinations$g2[i] %in% combinations$g1[1:(i - 1)]) {
    idx <- c(idx, i)
  }
}
combinations <- combinations[c(1, idx), ]
rownames(combinations) <- 1:nrow(combinations)

dist_p <- dist_t <- dist_coef <- matrix(0, nrow = N, ncol = N)
colnames(dist_p) <- rownames(dist_p) <- unique(df$g)
colnames(dist_t) <- rownames(dist_t) <- unique(df$g)
colnames(dist_coef) <- rownames(dist_coef) <- unique(df$g)

# create progress bar
if (verbose == TRUE) {
  pb <- txtProgressBar(min = 0, max = nrow(combinations), style = 3)
  k <- 1
}

for (i in 1:nrow(combinations)) {
  if (verbose == TRUE) {
    setTxtProgressBar(pb, k) # progress bar
    k <- k + 1
  }
  
  df$tmp <- "bg"
  df$tmp[df$g == combinations$g1[i]] <- "g1"
  df$tmp[df$g == combinations$g2[i]] <- "g2"
  
  design <- model.matrix(~ 0 + tmp + b + detrate, data = df)
  contrast_m <- makeContrasts(contrasts = c("tmpg1-tmpbg", "tmpg2-tmpbg"), levels = design)
  group_fit <- getGroupFit(dge, design, contrast_m, method = "trend") # limma trend
  
  idx1 <- rownames(dist_coef) == combinations$g1[i]
  idx2 <- colnames(dist_coef) == combinations$g2[i]
  dist_coef[idx1, idx2] <- cor(coef(group_fit)[, 1], coef(group_fit)[, 2])
  dist_t   [idx1, idx2] <- cor(group_fit$t[, 1], group_fit$t[, 2])
  dist_p   [idx1, idx2] <- cor(-log10(group_fit$p.value)[, 1] * sign(coef(group_fit)[, 1]),
                               -log10(group_fit$p.value)[, 2] * sign(coef(group_fit)[, 2])
  )
  
}
if (verbose == TRUE) {
  close(pb) # close progress bar
}
```

## Network

```{r cider-distance-network}
df_plot <- data.frame(g = seu.integrated$Group[select], # colour.by
                      b = seu.integrated$Batch[select], # batch
                      c = seu.integrated$initial_cluster[select], # label; initial cluster
                      stringsAsFactors = FALSE)

df_plot$combination <- paste0(df_plot$g, "-", df_plot$c)
freq <- table(df_plot$combination)
df_plot$freq <- freq[match(df_plot$combination, names(freq))]
df_plot <- df_plot[order(df_plot$freq, decreasing = TRUE), ]
df_plot <- unique(df_plot)

edges <- data.frame(from = combinations$g1, to = combinations$g2, weight = NA) # edges
tmp <- dist_coef + t(dist_coef)
for (i in 1:nrow(edges)) {
  edges$weight[i] <- tmp[rownames(tmp) == edges$from[i], colnames(tmp) == edges$to[i]]
}
edges$weight[edges$weight < 0] <- 0
edges <- edges[edges$weight > 0, ]
net <- igraph::graph_from_data_frame(edges, directed = FALSE)
E(net)$width <- 2^(E(net)$weight * 5)
vg_names <- attr(V(net), "names")

df_plot_cols <- data.frame(group = unique(df_plot$g),
                           col = col_vector[1:length(unique(df_plot$g))], stringsAsFactors = FALSE)
df_plot$col <- df_plot_cols$col[match(df_plot$g, df_plot_cols$group)]
V(net)$color <- df_plot$col[match(vg_names, df_plot$c)]

V(net)$frame.color <- "#777777"
V(net)$size <- 20 
V(net)$label.family <- "Helvetica"

plot(net); legend(
  x = -1.5, y = -1.1, df_plot_cols$group, pch = 21,
  col = "#777777", pt.bg = df_plot_cols$col, pt.cex = 2, cex = .8, bty = "n", ncol = 2
)
```

## Heatmap

```{r cider-dist-heatmap}
groups <- unique(df_plot$g)
idx1 <- paste0(groups, "_Batch1")
idx2 <- paste0(groups, "_Batch2")
tmp <- dist_coef + t(dist_coef)
diag(tmp) <- 1
pheatmap::pheatmap(
  tmp[idx1, idx2],
  cellwidth = 50,
  cellheight = 50,
  filename = paste0("plots/",dirsave,"/evaluation/IDER_similarity_heatmap.pdf"),
  border_color = "grey20",
  color = viridis::inferno(50),
  display_numbers = TRUE,
  cluster_rows = FALSE,
  cluster_cols = FALSE
)
```


```{r cider-dist-hierarchical-tree}
plot(hclust(as.dist(1- tmp)))
```

```{r}
for(i in 1:nrow(df_plot)){
  df_plot$similarity[i] <- tmp[paste0(df_plot$g[i], "_Batch1"), paste0(df_plot$g[i], "_Batch2")]
}
seu.integrated$similarity <- df_plot$similarity[match(seu.integrated$Group, df_plot$g)]
```

## tSNE plot

```{r cider-dist-plot, message=FALSE, warning=FALSE, fig.width=8, fig.height=4}
df_plot <- data.frame(V1 = dm@eigenvectors[,1],
                      V2 = dm@eigenvectors[,2],
                      label = seu.integrated$Group,
                      batch = seu.integrated$Batch,
                      similarity = seu.integrated$similarity)
p1 <- ggplot(df_plot, aes(x = V1, y = V2, fill = as.factor(label))) + geom_point(col = "grey40", size = 1, shape = 21) + theme_classic()  + theme(legend.position = "top") +  scale_fill_manual(breaks = unique(seu$Group), values = col_vector[1:3])
p2 <- ggplot(df_plot, aes(x = V1, y = V2, fill = as.factor(batch))) + geom_point(col = "grey40", size = 1, shape = 21)  +  theme_classic() + theme(legend.position = "top")  + scale_fill_manual(values = col_vector[9:10])
p3 <- ggplot(df_plot, aes(x = V1, y = V2, fill = similarity)) + geom_point(col = "grey40", size = 1, shape = 21)  +  theme_classic() + theme(legend.position = "top") +  scale_fill_viridis(option = "B")
p1 + p2 + p3
# ggsave(paste0("plots/",dirsave,"/evaluation/tsne_cca_tSNE_similarity.pdf"), width = 12, height = 4.5, useDingbats = FALSE)
```

## CMP

```{r}
i <- which(combinations$g1 == "CMP_Batch1" & combinations$g2 == "CMP_Batch2")
df$tmp <- "bg"
df$tmp[df$g == combinations$g1[i]] <- "g1"
df$tmp[df$g == combinations$g2[i]] <- "g2"

design <- model.matrix(~  0 + tmp + b + detrate, data = df) # design  
contrast_m <- makeContrasts(contrasts = c("tmpg1-tmpbg", "tmpg2-tmpbg"), levels = design) # contrast

logCPM <- cpm(dge, log = TRUE, prior.count = 3)
fit <- lmFit(logCPM, design)
group_fit <- contrasts.fit(fit, contrast_m)
group_fit <- eBayes(group_fit, trend=TRUE, robust = TRUE)

df_res <- data.frame(gene = rownames(group_fit), coef_batch1 = coef(group_fit)[,1], coef_batch2 = coef(group_fit)[,2])
# Refer to https://rpubs.com/iabrady/residual-analysis
fit <- lm(coef_batch2 ~ coef_batch1, data = df_res) 
df_res$predicted <- predict(fit)   
df_res$residuals <- residuals(fit) 
df_res$label <- FALSE
df_res$label[abs(df_res$residual) >= 1.8] <- TRUE
df_res$gene <- paste0("italic('",df_res$gene,"')")
ggplot(df_res, aes(x = coef_batch1, y = coef_batch2, label = gene)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +        # draw line from point to line
  geom_point(aes(fill = abs(residuals), size = abs(residuals)), shape = 21, colour = "grey20") +  # size of the points
  scale_fill_viridis_c(option = "plasma") +
  theme_bw() + 
  geom_text(hjust = -0.2, nudge_x = 0.05, data = df_res[df_res$label,], parse = TRUE) + xlim(-8, 8) + ylim(-6,6)
```

```{r}
i <- which(combinations$g1 == "MEP_Batch1" & combinations$g2 == "MEP_Batch2")
df$tmp <- "bg"
df$tmp[df$g == combinations$g1[i]] <- "g1"
df$tmp[df$g == combinations$g2[i]] <- "g2"

design <- model.matrix(~  0 + tmp + b + detrate, data = df) # design  
contrast_m <- makeContrasts(contrasts = c("tmpg1-tmpbg", "tmpg2-tmpbg"), levels = design) # contrast

logCPM <- cpm(dge, log = TRUE, prior.count = 3)
fit <- lmFit(logCPM, design)
group_fit <- contrasts.fit(fit, contrast_m)
group_fit <- eBayes(group_fit, trend=TRUE, robust = TRUE)

df_res <- data.frame(gene = rownames(group_fit), coef_batch1 = coef(group_fit)[,1], coef_batch2 = coef(group_fit)[,2])
# Refer to https://rpubs.com/iabrady/residual-analysis
fit <- lm(coef_batch2 ~ coef_batch1, data = df_res) 
df_res$predicted <- predict(fit)   
df_res$residuals <- residuals(fit) 
df_res$label <- FALSE
df_res$label[abs(df_res$residual) >= 1.8] <- TRUE
df_res$gene <- paste0("italic('",df_res$gene,"')")
ggplot(df_res, aes(x = coef_batch1, y = coef_batch2, label = gene)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +        # draw line from point to line
  geom_point(aes(fill = abs(residuals), size = abs(residuals)), shape = 21, colour = "grey20") +  # size of the points
  scale_fill_viridis_c(option = "plasma") +
  theme_bw() + 
  geom_text(hjust = -0.2, nudge_x = 0.05, data = df_res[df_res$label,], parse = TRUE) + xlim(-8, 8) + ylim(-6,6)
```

# Other evaluation metrics

## iLisi

```{r run-lisi}
X <- seu.integrated@reductions$tsne@cell.embeddings[,1:2]
meta_data <- seu.integrated@meta.data[,c("Batch","Group")]
lisi_res <- lisi::compute_lisi(X, meta_data, c("Batch","Group"))
colMeans(as.matrix(lisi_res))
```

```{r plot-lisi-output, fig.width=8, fig.height=4}
df_plot <- data.frame(Dimension_1 = dm@eigenvectors[,1],
                      Dimension_2 = dm@eigenvectors[,2],
                      label = seu.integrated$Group,
                      batch = seu.integrated$Batch,
                      cluster = seu.integrated$cluster,
                      batch_lisi = lisi_res$Batch,
                      group_lisi = lisi_res$Group)
p1 <- ggplot(df_plot, aes(x = Dimension_1, y = Dimension_2, fill = batch_lisi)) + geom_point(shape = 21, size = 2, col = "grey40") + theme_classic() + theme(legend.position = "top") +  viridis::scale_fill_viridis(option = "B", direction = -1)
p2 <- ggplot(df_plot, aes(x = Dimension_1, y = Dimension_2, fill = group_lisi)) + geom_point(shape = 21,  size = 2, col = "grey40") + theme_classic()  + theme(legend.position = "top") + viridis::scale_fill_viridis(option = "B", direction = -1)
plot_grid(p1, p2)

ggsave(paste0("plots/",dirsave,"/evaluation/lisi_tSNE_cca.pdf"), useDingbats = FALSE, width = 10, height = 5)
```

```{r plot-lisi-violin}
p1 <- ggplot(df_plot, aes(x = label, y = 3-group_lisi)) + geom_violin(scale = "width") + geom_boxplot(width = 0.05) + theme_classic() + xlab("") 
p2 <- ggplot(df_plot, aes(x = label, y = batch_lisi)) + geom_violin(scale = "width") + geom_boxplot(width = 0.05) + theme_classic() + xlab("")  
p1 + p2
ggsave(paste0("plots/",dirsave,"/evaluation/lisi_violinplot_bytypes.pdf"), useDingbats = FALSE, width = 8, height = 2)
```


```{r saverds}
seu.integrated$batch_lisi <- lisi_res$Batch
seu.integrated$group_lisi <- lisi_res$Group

saveRDS(df_plot, paste0("rdata/",dirsave,"/lisi_cca_integrated.rds"))
saveRDS(seu.integrated, paste0("rdata/",dirsave,"/seurat_object_cca_integrated.rds"), compress = TRUE)
rm(seu.integrated)
```

# Technical

```{r session-info}
sessionInfo()
```

